---
title: "Recursos computacionais"
output:
  html_document:
    toc: false
---

O curso não prevê conteúdo computacional. Entretanto todo o conteúdo
abordado pode ser tratado computacionalmente por  linguagens ou programas estatísticos.

Em particular, todo o conteúdo deste curso é confeccionado utilizando-se
o *software* [R](http://www.r-project.org), uma linguagem de programação
para estatística, que é livre e de código aberto. 

O uso de programas computacionais pode auxiliar o entendimento do
conteúdo do curso, e os códigos em R servem como ilustração para os
alunos interessados, mas não será parte da avaliação.

## Programa para estatística

- [The R project for Statistical Computing](http://www.r-project.org):
  página do programa **R**
  - [Curso sobre o uso do
  R](http://leg.ufpr.br/doku.php/sofware:material-r)
  - [RStudio](http://www.rstudio.org) um ambiente para facilitar
  uso do R
  - [Curso Básico do R](https://www.curso-r.com/material/r-base/)
  - [R-rautu](https://github.com/fernandomayer/R-rautu) uma introdução ao uso do R
  - [R-br](https://listas.inf.ufpr.br/cgi-bin/mailman/listinfo/r-br)
  é a lista de discussão em português sobre o uso do R
  - [Exercícios do livro texto](http://www.leg.ufpr.br/doku.php/pessoais:felipe) resolvidos com o uso do R (Seções 1,2 e 3)
  - [Outros materiais do R](https://www.curso-r.com/material/)